repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: check-ast
        language_version: python3.9
      - id: check-merge-conflict
      - id: check-case-conflict
      - id: check-json
      - id: check-toml
      - id: check-yaml
      - id: trailing-whitespace
        exclude: ^.*\.(lock)$||^docs\/
      - id: mixed-line-ending
        exclude: ^.*\.(lock)$||^docs\/
      - id: detect-private-key

  - repo: https://github.com/compilerla/conventional-pre-commit
    rev: v2.4.0
    hooks:
      - id: conventional-pre-commit
        stages: [commit-msg]

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: 'v0.3.2'
    hooks:
      - id: ruff-format
        name: Code formatting

      - id: ruff
        name: Code linting
        args:
          - --fix

  - repo: https://github.com/python-jsonschema/check-jsonschema
    rev: 0.28.0
    hooks:
      - id: check-github-workflows
        args:
          - "--verbose"


default_stages: [commit]
